objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_UUID__c</fullName>
        <externalId>true</externalId>
        <label>Contact UUID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/ProductDetailAPI.cls
@RestResource(urlMapping = '/ProductDetails/*')
global class ProductDetailAPI {
    
      @httpPost
    global static PricebookEntry displayProductdetails (String conExtUUId){
        
          RestRequest req = RestContext.request;
          RestResponse response = RestContext.response;   
       // String conExtUUId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        Contact objContact = [select id ,Home_Country__c, Product__c from contact where Contact_UUID__c =: conExtUUId ];                    
        PricebookEntry PBE = FetchProductDetails_CLS.getPricingDetails(objContact.Product__c,objContact.Home_Country__c);
        
        
        return PBE;
    
    }

    

}