objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <label>ATM Fee in other currencies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/FetchProductDetails_CLS.cls
public class FetchProductDetails_CLS {
    public static PricebookEntry getPricingDetails(Id idProduct,String strCountry){
        return [SELECT Id , ATM_Fee_in_other_currencies__c, UnitPrice, Card_Replacement_Cost__c,CurrencyIsoCode 
                FROM PricebookEntry 
                WHERE Product2Id =: idProduct AND Pricebook2.Home_Country__c=: strCountry AND IsActive =True LIMIT 1];  
    }
}